In [1]:
import sys
sys.path.insert(1, '../')

In [4]:
from src.data import DATASETS_LS, DATASETS_IMBLEARN, DATASETS_KEEL, load_dataset

In [5]:
len(DATASETS_IMBLEARN), len(DATASETS_KEEL), len(DATASETS_LS)

(24, 10, 34)

In [8]:
X_train, X_test, y_train, y_test = load_dataset("kddcup-buffer_overflow_vs_back")

X_train.head()

,0,2,3,4,5,9,12,13,15,16,...,29,30,31,32,35,36,37,38,39,40
781,0,0,0,54540,8314,2,1,0,0,0,...,0.0,0.0,255,255,0.0,0.0,0.00,0.00,0.03,0.03
1761,0,0,0,54540,8314,2,1,0,0,0,...,0.0,0.0,255,255,0.0,0.0,0.00,0.00,0.03,0.03
1923,0,0,0,54540,8314,2,1,0,0,0,...,0.0,0.5,255,255,0.0,0.0,0.00,0.00,0.04,0.04
1657,0,0,0,54540,8314,2,1,0,0,0,...,0.0,0.0,255,255,0.0,0.0,0.01,0.01,0.02,0.02
743,0,0,0,54540,8314,2,1,0,0,0,...,0.0,0.0,255,255,0.0,0.0,0.00,0.00,0.03,0.03

In [9]:
X_train, X_test, y_train, y_test = load_dataset("optical_digits")

X_train.head()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x54,x55,x56,x57,x58,x59,x60,x61,x62,x63
4017,0.0,0.0,0.0,11.0,5.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,12.0,2.0,0.0,0.0
2279,0.0,7.0,11.0,15.0,10.0,0.0,0.0,0.0,4.0,16.0,...,6.0,0.0,0.0,0.0,8.0,15.0,16.0,12.0,1.0,0.0
5322,5.0,16.0,13.0,1.0,0.0,0.0,0.0,0.0,9.0,14.0,...,11.0,0.0,0.0,5.0,16.0,14.0,10.0,8.0,6.0,0.0
3370,0.0,6.0,12.0,12.0,12.0,4.0,0.0,0.0,3.0,16.0,...,4.0,0.0,0.0,0.0,8.0,15.0,16.0,16.0,2.0,0.0
980,0.0,1.0,11.0,12.0,4.0,0.0,0.0,0.0,1.0,13.0,...,7.0,0.0,0.0,0.0,4.0,13.0,16.0,15.0,1.0,0.0